### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by lbighetti** [gothinkster/elixir-phoenix-realworld-example-app#12]

**Comment by rohanpujaris** [comment]
@lbighetti Anybody looking into all open issues currently. Would love to resolve them.

**Comment by lbighetti** [comment]
@rohanpujaris not currently. You are welcome to :)
Just leave a comment on which one you are working on so we can keep track in case someone else comes along.

**Comment by rohanpujaris** [comment]
@lbighetti Sure. Can you also check this PR if it looks good https://github.com/gothinkster/elixir-phoenix-realworld-example-app/pull/19

**Comment by rohanpujaris** [comment]
Working on this

**Comment by lbighetti** [comment]
Done in #21
