### ISSUE TITLE
where is the client side server? (aka no route found for GET / (RealWorldWeb.Router))

### ISSUE THREAD

**Issue by kordeviant** [gothinkster/elixir-phoenix-realworld-example-app#30]
how to serve the client side with this, please explain this in the repo.
using https://github.com/rtfeldman/elm-spa-example and changing api url to http://localhost:4000,
still i get error http://localhost:4000/api/articles?limit=10&offset=0 not found.

**Comment by fdenzer** [comment]
Hi,
what does Elm (which is a different language/web DSL) have to do with Elixir and Phoenix?
Both happen to be functional languages for web development. That’s where the similarities end. 

Should this issue be closed?
