### ISSUE TITLE
plug_cowboy dependency missing

### ISSUE THREAD

**Issue by thojanssens** [gothinkster/elixir-phoenix-realworld-example-app#34]
Hello, I cloned the repository then executed:

> cp config/dev.exs.example config/dev.exs
> mix deps.get
> mix ecto.create
> mix ecto.migrate
> mix phx.server

I have the following errors when executing `mix phx.server`:
> warning: please add the following dependency to your mix.exs:
> 
>     {:plug_cowboy, "~> 1.0"}
> 
> This dependency is required by Plug.Adapters.Cowboy
> which you may be using directly or indirectly.
> Note you no longer need to depend on :cowboy directly.
> 
> 
> [info] Application real_world exited: RealWorld.Application.start(:normal, []) returned an error: shutdown: failed to start child: RealWorldWeb.Endpoint
>     ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
>         ** (EXIT) "plug_cowboy dependency missing"
> ** (Mix) Could not start application real_world: RealWorld.Application.start(:normal, []) returned an error: shutdown: failed to start child: RealWorldWeb.Endpoint
>     ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
>         ** (EXIT) "plug_cowboy dependency missing"

**Comment by shdblowers** [comment]
fixed by #35
