### ISSUE TITLE
Could not compile dependency :comeonin, "mix compile" failed.

### ISSUE THREAD

**Issue by alefalves** [gothinkster/elixir-phoenix-realworld-example-app#39]
Heeey,

I'm running the following command: 
`mix ecto.create`

And the following occurs: 
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
could not compile dependency :comeonin, "mix compile" failed. You can recompile this dependency with "mix deps.compile comeonin", update it with "mix deps.update comeonin" or clean it with "mix deps.clean comeonin"`

I already install **make** and nothing changes.

I'm using macOS 10.15.1

**Comment by shdblowers** [comment]
I think this is an issue with xcode and you have to run something like `xcode-select --install` or something IIRC.
