### ISSUE TITLE
Implement Filters on index and feed

### ISSUE THREAD

**Issue by lbighetti** [gothinkster/elixir-phoenix-realworld-example-app#4]
## Current Behaviour

As pointed out by #3 we are ignoring params passed to `index` and `feed` on ArticleController
Passing `tag` for example will not filter the articles per tag

```elixir
  def index(conn, _params, user, _full_claims) do
    articles = Blog.list_articles()
               |> Repo.preload([:author, :favorites])
               |> Blog.load_favorites(user)
    render(conn, "index.json", articles: articles)
  end
```

## Expected Behaviour

Passing parameters to these functions should produce a filtered result.
For example `params = %{"tag" => "elixir"}` should return only articles with tag `elixir`

**Comment by rohanpujaris** [comment]
Working on this

**Comment by lbighetti** [comment]
@rohanpujaris i believe this is now complete is that correct ?

**Comment by rohanpujaris** [comment]
@lbighetti Yes, this is complete. We can close this

**Comment by lbighetti** [comment]
@rohanpujaris thanks!
